name: Continuous Delivery

on:
  push:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Fetches entire history, so we can analyze commits since last tag
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Bump version and push tag
      id: set-version
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
    - name: Publish to nuget.org
      uses: rohith/publish-nuget@v2
      if: ${{ steps.set-version.outputs.new_tag && github.ref == 'refs/heads/master' }}
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/Test.It.While.Hosting.Your.Console.Application/Test.It.While.Hosting.Your.Console.Application.csproj
        VERSION_STATIC: ${{ steps.set-version.outputs.new_version }}
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}